network: 'mainnet'
profile: true
csrfSecret: '1nt3rn3tsc@l3'
apiActive: true
logApiCalls: true
metaChainShardId: 4294967295
cron:
  transactionProcessor: true
  cacheWarmer: true
urls:
  elastic:
    - 'https://index.elrond.com'
  gateway:
    - 'https://gateway.elrond.com'
  privateApi:
    - 'http://localhost:4001'
  redis: '127.0.0.1'
  providers: 'https://internal-delegation-api.elrond.com/providers'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  delegationShardId: 2