network: 'devnet'
profile: true
csrfSecret: '1nt3rn3tsc@l3'
apiActive: true
logApiCalls: true
metaChainShardId: 4294967295
cron:
  transactionProcessor: true
  cacheWarmer: true
urls:
  elastic:
    - 'https://devnet-index.elrond.com'
  gateway:
    - 'https://devnet-gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://devnet-delegation.maiarbrowser.com/providers'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqp699jngundfqw07d8jzkepucvpzush6k3wvqyc44rx'
  delegationShardId: 2